node {   // can be run on ANY Jenkins processing node
   def commit_id
   stage('Preparation') {
     checkout scm  // sort of git clone, to have project files availabe
     sh "git rev-parse --short HEAD > .git/commit-id"  // get the commit id                      
     commit_id = readFile('.git/commit-id').trim()  // trim() gets rid of spaces and similar
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'  // zainstaluje dev time dependencies zadeklarowane w package.json (-> mocha)
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockezbyszekm/minimal-nodejs-apprhub') {  // using credentials store under dockerhub id credentials manager
       def app = docker.build("zbyszekm/minimal-nodejs-app:${commit_id}", '.').push() //second argument is the path for Dockerfile
     }
   }
}
